import "./globals.css";
import { Space_Grotesk } from "next/font/google";

// components
import { Navbar } from "@/components/Navbar";

const spaceGrotesk = Space_Grotesk({ subsets: ["latin"] });

export const metadata = {
  title: "User Search App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={spaceGrotesk.className}>
        <div className="grid min-h-screen bg-blue-950 place-content-center">
          <div>
            <Navbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
